export const globalSearch = [
  {
    title: "CPME",
    url: "/",
    keywords: [
      "Profissionais do Ensino",
      "Apoio",
      "Seguros sociais",
      "Empréstimos",
      "Acordos",
      "Parcerias",
      "Benefícios exclusivos",
      "Associado",
      "Caixa de Previdência do Ministério da Educação",
      "CPME",
      "Previdência",
      "Instituição",
      "Bem-estar",
      "Segurança Financeira",
      "Vantagens",
      "Simulação",
      "Proteção",
      "Seguro de maioridade",
      "Seguro de lazer",
      "Capitais diferidos com opção",
      "Capital repartido",
      "Capital duplo",
      "Seguro de vida  nteira",
      "Seguro de reforma",
      "Seguro de prosseguimento de estudos",
      "Cuidados de saúde",
      "Bolsas de estudo",
      "Aquisição de  equipamento educativo",
      "Arrendamento habitacional",
      "Arrendamento comercial",
      "Testemunhos",
    ],
  },
  {
    title: "Torne-se Associado",
    url: "/associados",
    keywords: [
      "cpme",
      "associados",
      "sócios",
      "aderir",
      "ensino",
      "inscrição",
      "estatuto",
      "proposta",
      "modalidade",
      "aprovação médica",
      "vantagens",
      "acordos",
      "parcerias",
      "emprestimos",
      "imoveis",
      "habitacionais",
      "comerciais",
      "arrendamento",
      "necessidades",
    ],
  },
  {
    title: "História",
    url: "/historia",
    keywords: [
      "Bem-estar",
      "Profissionais do ensino",
      "Caixa de Previdência do Ministério da Educação",
      "CPME",
      "1926",
      "Fundação",
      "Comunidade educativa",
      "Timeline",
      "História",
      "1925",
      "1932",
      "1934",
      "1935",
      "1937",
      "1946",
      "1991",
      "1993",
      "1997",
      "2001",
      "2008",
    ],
  },
  {
    title: "Estatutos",
    url: "/estatutos",
    keywords: [
      "cpme",
      "Estatutos da Caixa de Previdência do Ministério da Educação",
      "estatutos",
      "diário da república",
      "download",
      "detalhe",
      "detalhes",
    ],
  },
  {
    title: "Órgãos Sociais",
    url: "/orgaos-sociais",
    keywords: [
      "Orgãos sociais",
      "Caixa de Previdência do Ministério da Educação",
      "CPME",
      "Estrutura",
      "Administração",
      "Mesa da Assembleia Geral",
      "Conselho de Administração",
      "Conselho Fiscal",
      "cpme",
      "compromisso",
      "transparencia",
      "gestao",
      "associados",
      "serviço",
      "orgaos",
      "sociais",
      "proteção",
      "exercício",
      "assembleia",
      "mesa",
      "conselho",
      "geral",
      "administração",
      "fiscal",
    ],
  },
  {
    title: "Organograma",
    url: "/organograma",
    keywords: [
      "Organograma",
      "Assembleia Geral",
      "Conselho de Administração",
      "Conselho Fiscal",
      "Administrador Delegado",
      "Direção Técnica,  dministrativa e Recursos Humanos",
      "Atuário",
      "Jurídico",
      "Marketing e Comunicação",
      "Departamento Financeiro",
      "Departamento Sócios e  Operacional",
      "Departamento Património",
      "Tesouraria",
      "Gestão de Sócios",
      "Gestão de Imóveis",
      "Receita de Quotas",
      "Gestão de Tesouraria",
      "Novos Seguros Sociais",
      "Subsídios por Morte e Rendas Vitalícias",
      "Gabinete de Obras e Planeamento",
      "Gestão de Contratos Relativos a  Prédios",
      "Gestão Financeira e Contabilidade",
      "Gestão Financeira",
      "Contabilidade",
      "Gestão Operacional e Ação Complementar",
      "Informática",
      "Gestão de Contratos e Aprovisionamentos",
      "Gestão de Inquilinos e Pessoal",
      "Gestão de Inquilinos",
      "Gestão Pessoal Afeto aos Imóveis",
      "cpme",
      "geral",
      "assembleia",
      "conselho",
      "administração",
      "fiscal",
      "delegado",
      "recursos humanos",
      "atuario",
      "juridico",
      "marketing",
      "comunicação",
      "financeiro",
      "departamento",
      "operacional",
      "patrimonio",
      "tesouraria",
      "gestão",
      "socios",
      "imoveis",
      "contabilidade",
      "informatica",
      "contratos",
      "provisionamentos",
      "inquilinos",
      "afeto",
    ],
  },
  {
    title: "Relatórios e Contas CPME",
    url: "/relatorios-contas",
    keywords: [
      "cpme",
      "gestao",
      "detalhes",
      "relatorios",
      "contas",
      "Relatórios e contas",
      "Gestão",
      "2024",
      "2023",
      "2022",
      "2021",
      "2020",
      "2019",
      "2018",
      "2017",
      "2016",
      "2015",
      "2014",
      "2013",
      "2012",
      "2011",
      "2010",
      "2009",
      "2008",
    ],
  },
  {
    title: "Património",
    url: "/patrimonio",
    keywords: [
      "Património",
      "Futuro",
      "Soluções de arrendamento",
      "Arrendamento",
      "Lisboa",
      "Qualidade de vida",
      "Estabilidade",
      "Património Habitacional",
      "Património Comercial",
      "cpme",
      "patrimonio",
      "presente",
      "protegemos",
      "investir",
      "futuro",
      "soluções",
      "arrendamento",
      "comodidade",
      "comercial",
      "habitacional",
      "Empréstimos Apoio à Família",
      "Crédito à Habitação",
      "reservas matematicas",
      "Regulamento Empréstimo sobre Reservas Matemáticas e Quotas Pagas",
      "quotas",
      "quotas pagas",
      "Regulamento Novos Seguros",
      "Seguro de Prosseguimento de Estudos",
      "Seguro de Maioridade",
      "Capitais Diferidos com Opção",
      "Capital Repartido",
      "Capital Duplo",
    ],
  },
  {
    title: "Contratação Pública",
    url: "/contratacao-publica",
    keywords: [
      "Contratação Pública",
      "Processos",
      "Relatório de contratação",
      "Contratos",
      "cpme",
      "informacao",
      "processos",
      "contratação",
      "pública",
      "portaria",
      "contrato",
      "formação",
    ],
  },
  {
    title: "Regulamentos",
    url: "/regulamentos",
    keywords: [
      "Regulamentos",
      "Regulamento Estatuário",
      "Regulamentos Empréstimos",
      "Empréstimos",
      "Empréstimo apoio à família",
      "Empréstimos crédito à habitação",
      "Empréstimo sobre reservas matemáticas e quotas pagas",
      "Regulamentos seguros",
      "Seguros",
      "Novos Seguros",
      "Seguro de Prosseguimento de estudos",
      "Seguro de maioridade",
      "Capitais diferidos com opção",
      "Capital repartido",
      "Capital duplo",
      "cpme",
      "regulamento",
      "estatutario",
      "Empréstimos Apoio à Família",
      "Crédito à Habitação",
      "reservas matematicas",
      "Regulamento Empréstimo sobre Reservas Matemáticas e Quotas Pagas",
      "quotas",
      "quotas pagas",
      "Regulamento Novos Seguros",
      "Seguro de Prosseguimento de Estudos",
      "Seguro de Maioridade",
      "Capitais Diferidos com Opção",
      "Capital Repartido",
      "Capital Duplo",
    ],
  },
  {
    title: "Editais",
    url: "/editais",
    keywords: ["cpme", "editais", "socios", "associados", "edito"],
  },
  {
    title: "Acordos",
    url: "/acordos",
    keywords: [
      "cpme",
      "acordos",
      "rede de acordos",
      "instituições",
      "condições especiais",
      "áreas",
      "descontos",
      "socios",
      "associados",
      "parcerias",
      "apoio domiciliario",
      "saude",
      "residencias senior",
      "lazer",
      "outros acordos",
      "Acordos",
      "Instituições",
      "Serviços",
      "Descontos",
      "Condições exclusivas",
      "Rede de acordos",
      "Instituições parceiras",
      "Saúde",
      "Educação",
      "Lazer",
      "Outros acordos",
      "Apoio domiciliário",
    ],
  },
  {
    title: "Acordos - Apoio Domiciliario",
    url: "/acordo/apoio-domiciliario",
    keywords: [
      "Benefícios",
      "Coimbra",
      "Cuidado sublime",
      "Faro",
      "Cuidar & Cuidados",
      "Aveiro",
      "VitaLiving – Apoio domiciliário",
      "Viseu",
      "Conversas, cuidados e carinhos",
      "Setúbal Fisiolar – saúde e apoio domiciliário",
      "LisboApoio Lda – Apoio domiciliário",
      "Lisboa",
      "Momentos Felizes – Sénior Care",
      "Ponta Delgada",
      "Empathy – Serviço de Apoio Domiciliário",
      "Somos avós (triunfos na ribalta)",
      "Braga",
      "Domicare",
      "Casa dos pais",
      "Porto",
      "All day care",
      "Ponta delgada",
      "Habicuidados",
      "Conforto no futuro",
    ],
  },
  {
    title: "Acordos - Lazer",
    url: "/acordo/lazer",
    keywords: [
      "Hotéis",
      "Termas ",
      "Atividades de lazer",
      "Vitoria Stone Hotel",
      "Évora",
      "Vila Galé Hotéis",
      "Lisboa",
      "Vidago Palace Hotel",
      "Vila Real",
      "Viagens Abreu",
      "Porto",
      "TOPSPA Collection",
      "The Noble House - boutique hotel ",
      "Termas São Pedro do Sul",
      "Viseu",
      "Teatro Politeama",
      "Taipas Turitermas",
      "Braga",
      "Solinca Classica",
      "Setúbal",
      "Solar dos Araújo Coutinho – Casa dos Cavaleiros",
      "Sobreiras Alentejo Country Hotel - by Unlock Hotels",
      "Rosegarden House - by Unlock Boutique Hotels",
      "Pedras Salgadas Spa & Nature Park",
      "Parque Cerdeira | Gerês",
      "Palácio dos Condes de Anadia",
      "Palacete Chafariz D'El Rei - by Unlock Boutique Hotels",
      "Moxy Lisboa Oriente",
      "Monverde Wine Experience Hotel",
      "MAAT - Museu de Arte, Arquitetura e Tecnologia",
      "Jardins do Porto - Unlock Boutique Hotel",
      "Hotel Tryp Porto Expo",
      "Hotel Tryp Porto Centro",
      "Hotel Tryp Montijo Parque Hotel",
      "Hotel Tryp Lisboa Caparica Mar",
      "Hotel Tryp Leiria",
      "Leiria",
      "Hotel Star inn Porto",
      "Hotel Star inn Peniche",
      "Hotel Star inn Libon Aeroporto",
      "Hotel Meliã Setúbal",
      "Hotel Meliã Ria Hotel & SPA",
      "Hotel Meliã Madeira Mare Resort & SPA",
      "Hotel Meliã Lisboa Oriente",
      "Hotel Meliã Lisboa Aeroporto",
      "Hotel Meliã Castelo Branco",
      "Castelo Branco",
      "Hotel Meliã Braga Hotel & SPA",
      "Hotel InnSide Braga Centro",
      "Hotel Golden Residence Madeira",
      "Funchal",
      "Hotel do Templo & SPA (Hotéis do Bom Jesus)",
      "Hotel do Parque (Hotéis do Bom Jesus)",
      "Hotel do Mar",
      "Hotel do Lago (Hotéis do Bom Jesus)",
      "Hotel do Elevador (Hotéis do Bom Jesus)",
      "Hotel da Música",
      "Hotel D. Luís",
      "Coimbra",
      "Forrester Essence Douro Hotel - Boutique Hotel Experience",
      "DiverLanhoso - Atividades Desportivas",
      "Chaves - Termas & SPA",
      "Casa Museu Amália Rodrigues",
      "Casa Melo Alvim - Boutique Hotel",
      "Casa das Senhoras Rainhas - Boutique Hotel",
      "Azeites Casa Anadia",
      "Santarém",
      "Albergaria do Calvário - Boutique Hotel",
      "Évora",
      "ACP – Automóvel Club de Portugal",
    ],
  },
  {
    title: "Acordos - Residências Sénior",
    url: "/acordo/residencia-senior",
    keywords: [
      "Idosos",
      "Hotel Sénior",
      "Póvoa de Lanhoso, Braga",
      "Casa dos Pais",
      "Porto",
      "Chão do Grou",
      "Viseu",
    ],
  },
  {
    title: "Acordos - Saúde",
    url: "/acordo/saude",
    keywords: [
      "Clínicas",
      "Hospitais",
      "Khushi Minds",
      "Leiria",
      "Hospital Terra Quente (Mirandela) - Grupo HTQ",
      "Bragança",
      "Hospital Privado de Chaves - Grupo HTQ",
      "Vila Real",
      "+ Saúde Ortopedia e Bem Estar (Monção)",
      "Viana do Castelo",
      "Clínica de Santos",
      "Lisboa",
      "Miminho aos Avós",
      "Hospital Privado de Bragança - Grupo HTQ",
      "Fisiolar – Saúde e Apoio Domiciliário",
      "Setúbal",
      "Diatra - Centro de Diagnóstico e Tratamento Médico",
      "New Clinic",
      "Excellent Óptica",
      "Cuidar e Viver - Marques Inovação & Ambiente, S.A.",
      "Ponta Delgada",
      "Clínica de São Cristóvão",
      "A Farmácia Online",
      "Ideal Óptica da Malveira",
      "Farmácias Progresso",
      "Presmedenta - Clínica Médica Dentária Praça do Areeiro (As Clínicas)",
      "Euroroma - Consultório Médico e Dentário (As Clínicas)",
      "Falas e Palavras",
      "Aveiro",
      "Domus Óptica Picoas",
      "Domus Óptica Duque de Loulé",
      "José Carlos Simões Fernandes, (Dr.)",
      "CNO – Centro Neuroftalmológico de Lisboa",
      "Blueberry Clinic",
      "Clínica de Medicina Dentária Dr. Nuno Mendes Guimarães",
      "Oralklass - Clínicas Dentárias",
      "Clínica Cyrne",
      "Óptica Lab - Laboratórios de Lentes",
      "Clínica das Conchas",
      "Centro de Medicina Física e de Reabilitação Vimarlis",
    ],
  },
  {
    title: "Acordos - Outros Acordos",
    url: "/acordo/outros-acordos",
    keywords: [
      "Royal School of Languages",
      "Aveiro",
      "CLi – Centro de Línguas da Faculdade de Letras da ULisboa",
      "Lisboa",
      "Associação Nacional de Professores",
      "Braga",
      "Cambridge School Portugal",
      "Wall Street English",
    ],
  },
  {
    title: "Empréstimos",
    url: "/emprestimos",
    keywords: [
      "cpme",
      "Empréstimos",
      "Bem-estar",
      "Família",
      "Condições Especiais",
      "Empréstimos de apoio à família",
      "Bolsas de estudo",
      "Aquisição de equipamento educativo",
      "Cuidados de saúde",
      "Crédito à habitação",
      "Obras em casa própria",
      "Comprar ou construção",
      "Transferência de empréstimos",
      "Reservas Matemáticas",
      "Quotas Pagas",
    ],
  },
  {
    title: "Empréstimos - Bolsas de Estudo",
    url: "/emprestimo/bolsas-de-estudo",
    keywords: [
      "Bolsas de estudo",
      "Formação",
      "Educação",
      "Licenciaturas",
      "Mestrados",
      "Pós-Graduações",
      "MBAs",
      "Doutoramentos",
      "Cursos Técnicos",
    ],
  },
  {
    title: "Empréstimos - Aquisição de Equipamento Educativo",
    url: "/emprestimo/equipamento-educativo",
    keywords: ["Aquisição equipamento educativo", "Empréstimo exclusivo"],
  },
  {
    title: "Empréstimos - Cuidados de Saúde",
    url: "/emprestimo/cuidados-saude",
    keywords: [
      "Cuidados de saúde",
      "Saúde",
      "Médico",
      "Consultas",
      "Exames",
      "Cirurgias",
      "Tratamentos especializados",
    ],
  },
  {
    title: "Empréstimos - Obras em Casa Própria",
    url: "/emprestimo/obras-casa-propria",
    keywords: ["Obras", "Casa", "Casa própria", "Projetos", "Renovar"],
  },
  {
    title: "Empréstimos - Comprar ou Construção",
    url: "/emprestimo/comprar-ou-construir",
    keywords: [
      "Comprar",
      "Construção",
      "Solução crédito à habitação",
      "Financiamento",
      "Casa",
    ],
  },
  {
    title: "Empréstimos - Transferência de Empréstimo",
    url: "/emprestimo/transferencia-emprestimos",
    keywords: [
      "Transferência",
      "Empréstimos",
      "Crédito à habitação",
      "Taxa ",
      "Apoio",
      "Condições financeiras",
    ],
  },
  {
    title: "Empréstimos - Reservas Matemáticas",
    url: "/emprestimo/reservas-matematicas",
    keywords: [
      "Reservas matemáticas",
      "Despesas extraordinárias",
      "Reservas acumuladas",
      "Quotas pagas",
    ],
  },
  {
    title: "Empréstimos - Quotas Pagas",
    url: "/emprestimo/quotas-pagas",
    keywords: [
      "Reservas matemáticas",
      "Despesas extraordinárias",
      "Reservas acumuladas",
      "Quotas pagas",
    ],
  },
  {
    title: "Seguros Sociais",
    url: "/seguros-sociais",
    keywords: [
      "Seguros Sociais",
      "Proteção",
      "Bem-estar",
      "Soluções",
      "Seguros de Vida inteira",
      "Seguro de reforma",
      "Seguro de prosseguimento de estudos",
      "Seguro de maioridade",
      "Seguro de lazer",
      "Capitais diferidos com opção",
      "Capital repartido",
      "Capital duplo",
    ],
  },
  {
    title: "Seguros Sociais - Seguro de Vida Inteira",
    url: "/seguro-social/seguro-vida-inteira",
    keywords: ["Capital ", "Seguro", "Seguro de vida inteira"],
  },
  {
    title: "Seguros Sociais - Seguro de Reforma",
    url: "/seguro-social/seguro-reforma",
    keywords: [
      "Reforma",
      "Seguro de reforma",
      "Futuro",
      "65 anos",
      "Complemento financeiro",
      "Herdeiros",
    ],
  },
  {
    title: "Seguros Sociais - Seguro de Prosseguimento de Estudos",
    url: "/seguro-social/seguro-prosseguimento-estudos",
    keywords: [
      "Seguro prosseguimento estudos",
      "Jovens",
      "Estudos",
      "Curso médio",
      "Curso superior",
      "Despesas",
      "Formação profissional",
      "Percurso académico",
    ],
  },
  {
    title: "Seguros Sociais - Seguro de Maioridade",
    url: "/seguro-social/seguro-maioridade",
    keywords: [
      "Segurança",
      "Seguro de Maioridade",
      "Apoio",
      "Jovem",
      "Maioridade",
      "Adulto",
    ],
  },
  {
    title: "Seguros Sociais - Seguro de Lazer",
    url: "/seguro-social/seguro-lazer",
    keywords: ["Seguro de lazer", "Segurança", "Lazer"],
  },
  {
    title: "Seguros Sociais - Capitais Diferidos com Opção",
    url: "/seguro-social/capitais-diferidos",
    keywords: ["Capitais diferidos com opção", "Capital", "Proteção"],
  },
  {
    title: "Seguros Sociais - Capital Repartido",
    url: "/seguro-social/capital-repartido",
    keywords: ["Capital repartido", "Estabilidade", "Capital", "Família"],
  },
  {
    title: "Seguros Sociais - Capital Duplo",
    url: "/seguro-social/capital-duplo",
    keywords: ["Capital duplo", "Capital acordado", "Família", "Estabilidade"],
  },
  {
    title: "Arrendamento",
    url: "/arrendamento",
    keywords: [
      "Arrendamento",
      "Imóvel",
      "Soluções de arrendamento",
      "Imóvel habitacional",
      "Imóvel comercial",
      "Habitacional",
      "Comercial",
      "Lisboa",
      "Soluções",
      "Arrendamento comercial",
      "Arrendamento habitacional",
    ],
  },
  {
    title: "Notícias",
    url: "/noticias",
    keywords: ["cpme", "noticias"],
  },
  {
    title: "Contactos",
    url: "/contactos",
    keywords: [
      "Contactos",
      "Morada",
      "Localização",
      "Atendimento",
      "NIF",
      "Telefone",
      "Horário",
      "Email",
      "Formulário",
      "Associado",
      "Torne-se associado",
      "cpme",
    ],
  },
];
